config/routes.rb
Rails.application.routes.draw do

  root 'demo#index'

  get 'demo/index'
  get 'demo/about'
  get 'demo/contact'

  get 'menu' => 'access#menu'
  get 'login' => 'access#new'
  delete 'logout' => 'access#destroy'
  resource :access, controller: 'access', except: [:show, :edit, :update] do
    member do
      get :menu
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :subject

end

app/models/subject.rb
class Subject < ApplicationRecord

  has_many :pages

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

before_action :confirm_logged_in, :except => [:new, :create]

  # display menu
  def menu
    set_username
    @user_id = session[:user_id]
  end

  # display login form
  def new
  end

  # process login form
  def create
    # do login process here
    logger.info("*** Login process started")
    cookies[:username] = params[:username]
    session[:user_id] = 1483
    flash[:notice] = "Login in successful"
    redirect_to(menu_path)
  end

  # logout user
  def destroy
    # do logout process here
    session[:user_id] = nil
    redirect_to(login_path)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  layout 'application'

  protect_from_forgery with: :exception

  before_action :set_username
  before_action :set_language

  protected

    def set_username
      @username = cookies[:username]
    end

    def set_language
      @language = cookies[:language]
    end

    def confirm_logged_in
      if session[:user_id].present?
        return true
      else
        flash[:notice] = 'Please log in'
        redirect_to(login_path)
      end
    end

    def render_404
      filepath = Rails.root.join('public', '404.html')
      render(file: filepath, status: 404, layout: false) and return
    end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController

  def index
    # render(plain: "Just render text.")
    #
    # render(html: "<strong>HTML text</strong>")
    #
    # render(json: Subject.first)
    #
    # render(xml: ['dog', 'cat', 'mouse'])
    #
    # render(plain: 'OK', status: 200)
    #
    # render(file: "#{Rails.root}/public/404.html")
    #
    # send_file("#{Rails.root}/public/404.html")
    #
    # string = render_to_string(file: "#{Rails.root}/public/404.html")
    # logger.debug(string)


    # render('index')
  end

  def about
    render('about_us')
  end

  def contact
    if ['us', 'ca'].include?(params[:country])
      @phone = '(800) 555-6789'
    elsif params[:country] == 'uk'
      @phone = '(020) 7946 1234'
    else
      @phone = '+1 (987) 654-3210'
    end
    render('contact_us')
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :confirm_logged_in

  def index
    @pages = Page.order('position ASC')
  end

  def show
    @page = Page.find(params[:id])
  end

  def new
    @page = Page.new
  end

  def create
    # Instantiate a new object using form parameters
    @page = Page.new(page_params)
    # Save the object
    if @page.save
      # If save succeeds, redirect to the index action
      flash[:notice] = 'Page created'
      redirect_to(pages_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      flash[:notice] = 'Page updated'
      redirect_to(page_path(@page))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = 'Page destroyed'
    redirect_to(pages_path)
  end

  private

    def page_params
      params.require(:page).permit(
        :name,
        :visible,
        :position,
        :permalink,
        :content,
        :subject_id
      )
    end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  before_action :confirm_logged_in

  def index
    @subjects = Subject.order('position ASC')
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    # Instantiate a new object using form parameters
    @subject = Subject.new(subject_params)
    # Save the object
    if @subject.save
      # If save succeeds, redirect to the index action
      flash[:notice] = 'Subject created'
      redirect_to(subjects_path)
    else
      # If save fails, redisplay the form so user can fix problems
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      flash[:notice] = 'Subject updated'
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = 'Subject destroyed'
    redirect_to(subjects_path)
  end

  private

    def subject_params
      params.require(:subject).permit(:name, :visible, :position)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def error_messages_for(object)
    render(:partial => 'application/error_messages', :locals => {:object => object})
  end

  def status_tag(boolean, options={})
    options[:true_text] ||= ''
    options[:false_text] ||= ''

    if boolean
      content_tag(:span, options[:true_text], :class => 'status true')
    else
      content_tag(:span, options[:false_text], :class => 'status false')
    end
  end

end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/access/menu.html.erb
<% if flash[:notice].present? %>
  <div id="flash-notice" style="border: 1px solid red; color: red; padding: 10px;">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="access index">
  <h1>Menu</h1>

  <p> you are logged in as <%= @username %> (<%= @user_id %>) </p> 
  <p><%= link_to('Logout', logout_path, method: :delete) %> </p>
  <ul>
    <li><%= link_to('Manage Subjects', subjects_path) %></li>
    <li><%= link_to('Manage Pages', pages_path) %></li>
  </ul>
</div>

app/views/access/new.html.erb
<% content_for(:title) { 'Log In' } %>

<div class="access new">
  <h2>Welcome</h2>
  <p>A simulated log in form</p>

  <%= form_tag(access_path) do %>
    <table summary="login">
      <tr>
        <th><%= label_tag(:username) %></th>
        <td><%= text_field_tag(:username, params[:username]) %></td>
      </tr>
      <tr>
        <th><%= label_tag(:password) %></th>
        <td><%= password_field_tag(:password) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= submit_tag("Log In") %>
    </div>

  <% end %>
</div>

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="error-explanation">
    <h2><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/application/_flash.html.erb
<% if flash[:notice].present? %>
  <div id="flash-notice" style="border: 1px solid red; color: red; padding: 10px;">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/demo/about_us.html.erb
<% content_for(:title) { "About" } %>

<h1>About</h1>

<p>We believe that everyone should have access to top-quality widgets. It is the reason we first launched our line of premium widgets in 2000, and it is why we still feel passionate about making widgets today.</p>

<p>Stop relying on widget suppliers who mark up prices and may have limited inventory. We sell our full line of widgets direct to consumers online, and three-day shipping is always free. It has never been easier to buy widgets that meet your needs.</p>

<p><%= link_to('Contact Us', {:action => 'contact', :country => 'us'}) %></p>

app/views/demo/contact_us.html.erb
<% content_for(:title) { "Contact" } %>

<h1>Contact</h1>

<p>We are always happy to hear from our customers.</p>

<p>Phone: <%= @phone %></p>

<p>Press: <%= mail_to('press@nowhere.com') %></p>

<p><%= link_to('About Us', {:action => 'about'}) %></p>

app/views/demo/index.html.erb
<h1>This is the home page.</h1>

<%= link_to('All subjects', subjects_path) %>

<% content_for(:script) do %>
  <script>alert('Hello!');</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple CMS<%= ' - ' + yield(:title) if content_for?(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:script) %>
  </head>

  <body>

    <header>
      <span id="logo">Simple CMS</span>
      <% if session[:user_id].present? %>
        <span style="float: right;">
          User: <%= @username %>
          <%= link_to(logout_path, method: :delete) do %>
            <%= image_tag('icon_logoff.png', size: '14x14', title: 'logout') %>
          <% end %>
        </span>
      <% end %>
    </header>

    <div id="content">
      <%= render(partial: 'application/flash') %>
      <%= yield %>
    </div>

    <footer>
      Copyright <%= Time.now.year %>
    </footer>

  </body>
</html>

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page form fields">
  <tr>
    <th>Subject</th>
    <td><%= f.select(:subject_id, Subject.all.map {|s| [s.name, s.id]}) %></td>
  </tr>
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <% count = Page.count + (f.object.new_record? ? 1 : 0) %>
    <td><%= f.select(:position, 1..count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, :rows => 10, :cols => 60) %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<% content_for(:title) { "Delete Page: #{@page.name}" } %>

<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>

  <%= form_for(@page, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>
    <p><%= @page.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<% content_for(:title) { "Edit Page: #{@page.name}" } %>

<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages edit">
  <h2>Update Page</h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<% content_for(:title) { "Pages" } %>

<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path, :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Page</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.subject.name %></td>
      <td><%= page.name %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="actions">
        <%= link_to("Show", page_path(page), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<% content_for(:title) { "New Page" } %>

<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(@page) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<% content_for(:title) { "Page: #{@page.name}" } %>

<%= link_to("<< Back to List", pages_path, :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Page detail view">
    <tr>
      <th>Subject Name</th>
      <td><%= @page.subject.name %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= simple_format(word_wrap(strip_tags(@page.content.to_s))) %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at.to_s(:long) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at.to_s(:long) %></td>
    </tr>
  </table>

</div>

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Subject form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <% count = Subject.count + (f.object.new_record? ? 1 : 0) %>
    <td><%= f.select(:position, 1..count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td>
      <%= f.radio_button(:visible, '1') %> Yes
      <%= f.radio_button(:visible, '0') %> No
    </td>
  </tr>
</table>

app/views/subjects/delete.html.erb
<% content_for(:title) { "Delete Subject: #{@subject.name}" } %>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>

  <%= form_for(@subject, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>
    <p><%= @subject.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<% content_for(:title) { "Edit Subject: #{@subject.name}" } %>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<% content_for(:title) { 'Subjects' } %>

<div class="subjects index">
  <h2>Subjects</h2>

  <%= link_to("Add New Subject", new_subject_path, :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= status_tag(subject.visible) %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<% content_for(:title) { 'New Subject' } %>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/show.html.erb
<% content_for(:title) { "Subject: #{@subject.name}" } %>

<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Pages</th>
      <td><%= pluralize(@subject.pages.count, 'page') %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at.to_s(:long) %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at.strftime("%m/%d/%Y %I:%M %p") %></td>
    </tr>
  </table>

</div>